"""Candidate profile template with optional local overrides.

Tracked file stays generic. Personal local data should live in
``src/profile_local.py`` which is gitignored.
"""
from __future__ import annotations

PROFILE = {
    "name": "candidate name",
    "email": "",
    "location": "Fairfax, VA",
    "preferred_locations": [
        "Fairfax, VA",
        "Marietta, GA",
        "Atlanta, GA",
        "Georgia",
        "Texas",
        "Irving, TX",
        "Ohio",
        "Fairborn, OH",
        "Pennsylvania",
        "Downingtown, PA",
        "Philadelphia, PA",
    ],
    "location_addresses": {
        "Fairfax, VA": "Fairfax, VA",
        "Atlanta / Georgia": "Marietta, GA",
        "Texas": "Irving, TX",
        "Ohio": "Fairborn, OH",
        "Pennsylvania / Philadelphia": "Downingtown, PA",
    },
    "experience_years": 3,
    "education": "M.S. Data Analytics Engineering - George Mason University (Dec 2025)",
    "certifications": [
        "Microsoft Certified: Azure DevOps Engineer Expert (AZ-400)",
        "Microsoft Certified: Azure Developer Associate (AZ-204)",
        "Microsoft Certified: Azure AI Fundamentals (AI-900)",
        "Microsoft Certified: Azure Fundamentals (AZ-900)",
        "Google Cloud certifications",
        "Salesforce Superbadges (3)",
        "FinTech Specialization (HKUST)",
        "Self-Driving Cars Specialization (University of Toronto)",
    ],
    "target_roles": [
        "Data Scientist",
        "Data Engineer",
        "Data Analyst",
        "Financial Analyst",
        "Operations Analyst",
        "Research Analyst",
        "Financial Data Analyst",
        "Operations Data Analyst",
        "Research Data Analyst",
        "Analytics Engineer",
        "Machine Learning Engineer",
        "Machine Learning Scientist",
        "MLOps Engineer",
        "Applied Scientist",
        "AI Engineer",
        "Decision Scientist",
        "Research Scientist",
        "Business Intelligence Analyst",
        "Business Intelligence Engineer",
        "Business Intelligence Developer",
        "Data Warehouse Engineer",
        "ML/AI Data Engineer",
        "Product Analyst",
        "Business Analyst",
        "Insights Analyst",
        "Insights Engineer",
        "Reporting Analyst",
        "Product Analytics Engineer",
        "Forecasting Analyst",
        "Experimentation Analyst",
        "Data Platform Engineer",
        "LLM Engineer",
        "Prompt Engineer",
    ],
    "contact_phone": "",
    "linkedin_url": "",
    "github_url": "",
}

SKILLS_STRONG: set[str] = {
    "a/b testing",
    "airflow",
    "apache spark",
    "attention mechanisms",
    "automated retraining",
    "aws",
    "azure",
    "bash",
    "beautifulsoup",
    "bigquery",
    "chroma",
    "chromadb",
    "ci/cd",
    "caching",
    "circuit breaker",
    "cohort analysis",
    "collaborative filtering",
    "consensus forecasting",
    "codex",
    "cost optimization",
    "cors",
    "cross-functional collaboration",
    "customer segmentation",
    "cursor",
    "dashboarding",
    "dashboard development",
    "data governance",
    "data lineage",
    "data quality",
    "data modeling",
    "data privacy",
    "data compliance",
    "data visualization",
    "data warehouse",
    "databricks",
    "dbt",
    "docker",
    "docker compose",
    "drift detection",
    "duckdb",
    "emissions analytics",
    "elt",
    "etl",
    "event streaming",
    "faiss",
    "financial modeling",
    "fastapi",
    "feature engineering",
    "forecasting",
    "funnel analysis",
    "git",
    "github",
    "github actions",
    "gcp",
    "glue",
    "geopandas",
    "geospatial analytics",
    "google analytics",
    "grounded outputs",
    "growth analytics",
    "hadoop",
    "behavioral analytics",
    "backtesting",
    "bollinger bands",
    "hugging face",
    "hugging face transformers",
    "java",
    "kafka",
    "kpi tracking",
    "kpi reporting",
    "kinesis",
    "kubernetes",
    "lambda",
    "latency optimization",
    "lightgbm",
    "linux",
    "llmops",
    "llm evaluation",
    "llm fine-tuning",
    "lru cache",
    "lstm",
    "layer normalization",
    "machine learning",
    "matplotlib",
    "mcp",
    "mcp http bridge",
    "metadata management",
    "ml",
    "mlflow",
    "model monitoring",
    "model deployment",
    "mongodb",
    "monte carlo",
    "multi-asset forecasting",
    "mysql",
    "nltk",
    "numpy",
    "openai api",
    "ohlcv",
    "observability",
    "business operations",
    "operations research",
    "operational alerting",
    "performance metrics",
    "pipeline",
    "personalization",
    "portfolio analytics",
    "postgres",
    "postgresql",
    "parameterized queries",
    "power bi",
    "pydantic",
    "prompt engineering",
    "process improvement",
    "product analytics",
    "product experimentation",
    "pyspark",
    "python",
    "pytorch",
    "query success",
    "quicksight",
    "quality assurance",
    "query optimization",
    "rag",
    "risk-adjusted returns",
    "report generation",
    "redshift",
    "real-time pipelines",
    "real-time scoring",
    "recommendation systems",
    "retention analysis",
    "rest api",
    "rest api design",
    "rate limiting",
    "r",
    "s3",
    "sagemaker",
    "scikit-learn",
    "schema management",
    "schema validation",
    "security hardening",
    "sklearn",
    "shap",
    "snowflake",
    "spark",
    "sql",
    "sql injection prevention",
    "sql server",
    "stdio protocol",
    "streamlit",
    "statsmodels",
    "sector rotation",
    "sharpe ratio",
    "tableau",
    "tableau desktop",
    "tableau prep",
    "tensorflow",
    "time series",
    "technical indicators",
    "transfer learning",
    "transformer",
    "transformer architectures",
    "grounding",
    "hallucination detection",
    "hallucination mitigation",
    "provenance",
    "user retention",
    "uv",
    "uvicorn",
    "vix",
    "volatility modeling",
    "walk-forward validation",
    "excel",
    "microsoft excel",
    "ms excel",
    "stakeholder management",
    "data validation",
    "data integrity",
    "access control",
    "openapi",
    "json-rpc",
    "plotly",
    "input validation",
    "yfinance",
    "xgboost",
}

SKILLS_MODERATE: set[str] = {
    "ab test",
    "alteryx",
    "arima",
    "agentic workflows",
    "azure devops",
    "chain-of-thought prompting",
    "attention over timesteps",
    "climate analytics",
    "cloud data services",
    "cross-asset dependencies",
    "directional forecasting",
    "expanding window backtesting",
    "experimentation",
    "feature scaling",
    "google cloud",
    "hive",
    "hql",
    "looker",
    "evaluation harness",
    "ab testing",
    "churn analysis",
    "high-conviction signals",
    "lstm-arima consensus",
    "macd",
    "macro feature engineering",
    "market regime analysis",
    "max drawdown",
    "pytest",
    "regime detection",
    "rolling volatility",
    "rsi",
    "sequence modeling",
    "signal generation",
    "slippage modeling",
    "threshold tuning",
    "transaction cost modeling",
    "walk-forward evaluation",
}

try:
    from .profile_local import PROFILE as LOCAL_PROFILE
    from .profile_local import SKILLS_MODERATE as LOCAL_SKILLS_MODERATE
    from .profile_local import SKILLS_STRONG as LOCAL_SKILLS_STRONG
except ImportError:
    LOCAL_PROFILE = None
    LOCAL_SKILLS_STRONG = None
    LOCAL_SKILLS_MODERATE = None

if isinstance(LOCAL_PROFILE, dict):
    PROFILE = LOCAL_PROFILE
if isinstance(LOCAL_SKILLS_STRONG, set):
    SKILLS_STRONG = LOCAL_SKILLS_STRONG
if isinstance(LOCAL_SKILLS_MODERATE, set):
    SKILLS_MODERATE = LOCAL_SKILLS_MODERATE

_STRONG_BONUS = 8
_MODERATE_BONUS = 3


def skill_bonus(text: str, cap: int = 20) -> int:
    """Return a skill-match bonus (0-cap) based on skills found in ``text``."""
    t = (text or "").lower()
    bonus = 0
    for skill in SKILLS_STRONG:
        if skill in t:
            bonus += _STRONG_BONUS
    for skill in SKILLS_MODERATE:
        if skill in t:
            bonus += _MODERATE_BONUS
    return min(bonus, cap)


def profile_summary_html() -> str:
    return (
        f"<p style='font-size:12px;color:#666;margin:0 0 8px'>"
        f"Matched for <strong>{PROFILE['name']}</strong> - "
        f"targeting <em>{', '.join(PROFILE['target_roles'][:4])}...</em></p>"
    )


def profile_summary_text() -> str:
    return (
        f"Profile: {PROFILE['name']} | "
        f"Target: {', '.join(PROFILE['target_roles'][:3])}..."
    )
